on: [workflow_dispatch]

jobs:
  zap_scan:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://ginandjuice.shop'
